ingress: Fix conformance test for trailing slash handling
This commit is to fix the below conformance test failure, which can be
summarized as per below:

- Scenario 1: PathType: Prefix, Path: /foo
  For this scenario, any path such as /foobar should not be matched

- Scenario 2: PathType: Prefix, Path: /foo/
  For this scenario, the trailing slash should not be considered i.e. /foo
  should be matched.

The changes in this PR is to change Prefix match to SafeRegex match with
below expression <removed trailing slash>(/.*)?$.

```
Failed steps:

  Scenario: An Ingress with prefix path rules should match each labels string prefix # features/path_rules.feature:161
    Then the response status-code must be 404 # features/path_rules.feature:165
      Error: expected status code 404 but 200 was returned

  Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    Then the response status-code must be 200 # features/path_rules.feature:185
      Error: expected status code 200 but 404 was returned

5 scenarios (2 passed, 3 failed)
37 steps (29 passed, 3 failed, 5 skipped)
1m45.93343714s
```

Relates to #19306

Signed-off-by: Tam Mach <tam.mach@isovalent.com>