test: Delete hubble-ca-secret when cleaning up
Remove hubble-ca-secret when cleaning up Cilium components. This may help
avoid test fails installing Cilium with this error message:

  Error: rendered manifests contain a resource that already
  exists. Unable to continue with install: existing resource conflict:
  kind: Secret, namespace: kube-system, name: hubble-ca-secret

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>