ingress: Fix conformance test for single DNS match
This commit is to fix the below conformance test failure. For example,
*.foo.com in Ingress expects one and only one single subdomain e.g.
bar.foo.com, while envoy allows multiple subdomains e.g. baz.bar.foo.com.
The approach is to add extra header matching to enforce that host/authority
should not have any dot character for wildcard part.

```
--- Failed steps:

  Scenario: An Ingress with a wildcard host rule should not route traffic matching on more than a single dns label # features/host_rules.feature:78
    Then the response status-code must be 404 # features/host_rules.feature:82
      Error: expected status code 404 but 200 was returned
```

Signed-off-by: Tam Mach <tam.mach@isovalent.com>