bpf: Protect ipv4_redirect_to_host_port() with LXC_IPV4
The caller is protected by LXC_IPV4 as well. Fixes the following
error:
In file included from /var/lib/cilium/bpf/bpf_lxc.c:38:
  /var/lib/cilium/bpf/lib/lxc.h:93:29: error: use of undeclared identifier 'LXC_IPV4'
  .saddr = __constant_htonl(LXC_IPV4),

Fixes: 76df86b6cca3bc2 ("proxy: Initial transparent proxy support")
Signed-off-by: Thomas Graf <thomas@cilium.io>