bpf: Fix complication issue when ENABLE_L7_LB is set
This commit is to fix the below complication issue, when IPv6 only + L7
LB are enabled.

```
level=error msg="Failed to compile bpf_lxc.dbg.o: exit status 1" compiler-pid=3406 linker-pid=3407 subsys=datapath-loader
level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:201:36: error: member reference type 'struct ipv6_ct_tuple' is not a pointer; did you mean to use '.'?" subsys=datapath-loader
level=debug msg="                cilium_dbg3(ctx, DBG_L7_LB, tuple->daddr.p4, tuple->saddr.p4," subsys=datapath-loader
level=debug msg="                                            ~~~~~^~" subsys=datapath-loader
level=debug msg="                                                 ." subsys=datapath-loader
level=debug msg="/var/lib/cilium/bpf/bpf_lxc.c:201:53: error: member reference type 'struct ipv6_ct_tuple' is not a pointer; did you mean to use '.'?" subsys=datapath-loader
level=debug msg="                cilium_dbg3(ctx, DBG_L7_LB, tuple->daddr.p4, tuple->saddr.p4," subsys=datapath-loader
level=debug msg="                                                             ~~~~~^~" subsys=datapath-loader
level=debug msg="                                                                  ." subsys=datapath-loader
level=debug msg="2 errors generated." subsys=datapath-loader
```

Signed-off-by: Tam Mach <tam.mach@cilium.io>