ci: Use correct `agent` value in preflight check
The `K8sUpdates` deploys the Helm preflight check on top of an existing
older Cilium installation. To deploy the preflight check, the agent
must be disabled. The flag to disable the agent has been renamed in the
Cilium 1.9 charts. Therefore the upgrade test needs to set the proper
value.

This fixes an issue with the upgrade test on GKE where it fails as
follows:

```
coalesce.go:165: warning: skipped value for agent: Not a table.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ResourceQuota, namespace: cilium, name: cilium-resource-quota
```

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>