ipsec, bpf: fix build error when tunneling is disabled
If we don't have encap index defined (ENCAP_IFINDEX), then we also cannot
redirect to it. This compilation error is thrown instead:

  2019-03-16T08:38:33.30268603Z level=warning msg="/var/lib/cilium/bpf/bpf_netdev.c:548:11: warning: implicit declaration of function '__encap_and_redirect_with_nodeid' is invalid in C99 [-Wimplicit-function-declaration]" subsys=daemon
  2019-03-16T08:38:33.302694714Z level=warning msg="                        return __encap_and_redirect_with_nodeid(skb, tunnel_endpoint, seclabel, TRACE_PAYLOAD_LEN);" subsys=daemon
  2019-03-16T08:38:33.302702926Z level=warning msg="                               ^" subsys=daemon
  2019-03-16T08:38:33.302708262Z level=warning msg="1 warning generated." subsys=daemon

Fixes: 8d9c282bd928 ("cilium: ipsec, add BPF datapath encryption direction")
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>