bpf: remove unused but set variable in handle_netdev
This fixes the following error when building with clang 15:

    bpf_host.c:1057:25: error: variable 'tunnel_ep' set but not used [-Werror,-Wunused-but-set-variable]
             __u32 *vrf_id, dst_id, tunnel_ep = 0;
                                    ^

Fixes: f42f1dec79e7 ("bpf: Perform SRv6 policy lookup")

Signed-off-by: Tobias Klauser <tobias@cilium.io>