ipam: Fix race in NodeManager.Resync
TestNodeManagerManyNodes had been flaky before ported from aws/eni,
and was eventually disabled in aws tests:
https://github.com/cilium/cilium/issues/11560

One of the sources of this flake is the races in the values of metricsapi,
e.g. `metricsapi.Nodes("total")` and `metricsapi.AllocatedIPs("available")`,
which is not protected from concurrent writes in NodeManager.Resync.

Allowing multiple goroutines to execute Resync simultaneously doesn't
really make sense, since `Node.resyncNode` is already executed in parallel
and controlled by semaphore.
this patch serializes NodeManager.Resync to avoid data races on metricsAPI.

Some excerpts of failed tests:
    --- FAIL: Test (17.29s)
        --- FAIL: Test/IPAMSuite (17.29s)
            --- FAIL: Test/IPAMSuite/TestIPAMMetadata (0.01s)
                testing.go:1446: race detected during execution of test
            --- FAIL: Test/IPAMSuite/TestNodeManagerManyNodes (3.88s)
                node_manager_test.go:610:
                    ... obtained int = 850
                    ... expected int = 1000

    --- FAIL: Test (17.74s)
        --- FAIL: Test/IPAMSuite (17.74s)
            --- FAIL: Test/IPAMSuite/TestNodeManagerManyNodes (4.36s)
                node_manager_test.go:606:
                    ... obtained int = 87
                    ... expected int = 100

Related: #26617
Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>