Ginkgo: Fix issue with Jenkinsfile
Issue introduced by commit `2548b548ad77b350635d03e3046156ea0b43d6c4`

Current error message:

```
Obtained ginkgo.Jenkinsfile from git https://github.com/cilium/cilium.git
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 32: The post section can only contain build condition names with code blocks. Valid condition names are [always, changed, aborted, failure, success, unstable, notBuilt] @ line 32, column 17.
                   sh "cd ${TESTDIR}; make clean-ginkgo-tests || true"
                   ^

WorkflowScript: 31: post can not be empty @ line 31, column 13.
               post {
```

Build ID: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/556/console

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>