kvstore/allocator: Fix staticchecker warnings
Fixes the following warnings:
pkg/kvstore/allocator/allocator.go:242:37: should use make(chan struct{}) instead (S1019)
pkg/kvstore/allocator/allocator.go:262:25: error strings should not be capitalized (ST1005)
pkg/kvstore/allocator/allocator.go:270:25: error strings should not be capitalized (ST1005)
pkg/kvstore/allocator/cache.go:235:17: func (*cache).startAndWait is unused (U1000)
pkg/kvstore/allocator/cache.go:242:20: error strings should not be capitalized (ST1005)

Signed-off-by: Thomas Graf <thomas@cilium.io>