bpf: tests: rename a variable to prevent build failure
Build of a test will fail if a 'key' variable is defined, like this:

    wildcard_lookup.c:123:2: error: declaration shadows a local variable [-Werror,-Wshadow]
            test_init();
            ^
    ./common.h:198:9: note: expanded from macro 'test_init'
                    __u32 key = 0;                                            \
                          ^
    wildcard_lookup.c:113:17: note: previous declaration is here
            struct lb4_key key = {
                           ^
    wildcard_lookup.c:348:2: error: declaration shadows a local variable [-Werror,-Wshadow]
            test_init();
            ^
    ./common.h:198:9: note: expanded from macro 'test_init'
                    __u32 key = 0;                                            \
                          ^
    wildcard_lookup.c:328:17: note: previous declaration is here
            struct lb6_key key = {
                           ^

Fix this by renaming a variable used in test setup macros.

Signed-off-by: Anton Protopopov <aspsk@isovalent.com>