Makefile: Check values.yaml for modifications
As of commit e25a218d, we generate the `values.yaml` from
`values.yaml.tmpl`. The Makefile automatically regenerates the
`values.yaml` file when the template is modified.

The reverse however is not true, i.e. if a developer accidentally
modifies the `values.yaml` file and runs `make -C install/kubernetes`,
nothing happens. This is due the fact that the user-modified
`values.yaml` will have a newer timestamp than the `values.yaml.tmpl`
and thus `make` will consider everything up to date. This makes it hard
to spot this mistake locally, as there is no error or warning that the
wrong file was modified.

One potential option would be to make the `cilium/values.yaml` target
PHONY that the two files are always in sync, however this will overwrite
any accidental changes by the user without backup or warning.

This commit therefore takes a different approach by introducing a new
`check-values-yaml` target. This target performs the template
substitution for `values.yaml.tmpl` to stdout and compares it to the
`values.yaml` file in the work-tree. If there are differences between
the two files, the target fails. See the output below for an example.

The `check-values-yaml` target is added to the virtual `all` target to
ensure it is executed by default, but only after `update-versions` has
been run to ensure it always checks against the most recent version of
`values.yaml`.

```console
$ make -C install/kubernetes
make: Entering directory '/home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes'
: cilium/Chart.yaml
grep -lR -e 'version:' -e 'appVersion:' /home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes/cilium/ \
	| xargs -L 1  sed -i -e 's/''\([vV]ersion:\) ''[0-9]\+\.[0-9]\+\.[0-9]\+.*''/\1 '1.12.90'/g'
sed -i 's;icon:.*;icon: https://cdn.jsdelivr.net/gh/cilium/cilium@master/Documentation/images/logo-solo.svg;' "/home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes/cilium/Chart.yaml"
:  check-values-yaml
( echo -e "# File generated by install/kubernetes/Makefile; DO NOT EDIT." > /dev/stdout; echo -e "# This file is based on install/kubernetes/cilium/values.yaml.tmpl.\n" >> /dev/stdout; envsubst < /home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes/cilium/values.yaml.tmpl >> /dev/stdout ) \
	| diff -u - "/home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes/cilium/values.yaml" \
	|| (echo -e "\nerror: cilium/values.yaml has been modified"; \
		echo "Make sure to apply your changes to cilium/values.yaml.tmpl and run 'make -C install/kubernetes cilium/values.yaml' to regenerate."; exit 1)
--- -	2022-06-28 11:40:22.284171162 +0200
+++ /home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes/cilium/values.yaml	2022-06-28 11:40:20.337565433 +0200
@@ -29,7 +29,7 @@
   name: default
   # -- (int) Unique ID of the cluster. Must be unique across all connected
   # clusters and in the range of 1 to 255. Only required for Cluster Mesh.
-  id:
+  id: 0

 # -- Define serviceAccount names for components.
 # @default -- Component's fully qualified name.

error: cilium/values.yaml has been modified
Make sure to apply your changes to cilium/values.yaml.tmpl and run 'make -C install/kubernetes cilium/values.yaml' to regenerate.
make: *** [Makefile:48: check-values-yaml] Error 1
make: Leaving directory '/home/gandro/Isovalent/go/src/github.com/cilium/cilium/install/kubernetes'
```

Reported-by: Fabio Falzoi <fabio.falzoi@isovalent.com>
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>