Test: Fix bugtool on kubernetes 1.7
On kubernetes 1.7 the cp need to have a specific destination, and the
`kubectl cp` command was failing:

```
vagrant@k8s1:~$ kubectl cp kube-system/cilium-jk0kn:/tmp/cilium-bugtool-20180403-065927.547+0000-UTC-039557248.tar /tmp/
tar: Removing leading `/' from member names
error: open /tmp: is a directory
```

I added a new param to the command and now works as expected
```
vagrant@k8s1:~$ kubectl cp kube-system/cilium-jk0kn:/tmp/cilium-bugtool-20180403-065927.547+0000-UTC-039557248.tar /tmp/cilium-bugtool-20180403-065927.547+0000-UTC-039557248.tar
tar: Removing leading `/' from member names
vagrant@k8s1:~$
```

Related to #3475

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>