helm: Correct typo in Ingress validation
This is to correct the typo (i.e. l7Proxy instead of l7proxy)
in helm validation if Ingress or Gateway API is enabled. Negative
testing is done as per below

```
$ helm template --namespace kube-system cilium "./install/kubernetes/cilium" --set ingressController.enabled=true --set l7Proxy=false
Error: execution error at (cilium/templates/validate.yaml:52:9): Ingress or Gateway API controller requires .Values.l7Proxy to be set to 'true'

$ helm template --namespace kube-system cilium "./install/kubernetes/cilium" --set gatewayAPI.enabled=true --set l7Proxy=false
Error: execution error at (cilium/templates/validate.yaml:52:9): Ingress or Gateway API controller requires .Values.l7Proxy to be set to 'true'

```

Fixes: 4e9929fdc76e684b77504f93165ad070485f1d71

Reported-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>
Signed-off-by: Tam Mach <tam.mach@cilium.io>