kvstore/etcd: Fix staticchecker warnings
Fixes the following warnings:
pkg/kvstore/etcd.go:326:2: should use a simple channel send/receive instead of select with a single case (S1000)
pkg/kvstore/etcd.go:347:20: error strings should not be capitalized (ST1005)
pkg/kvstore/etcd.go:441:25: error strings should not be capitalized (ST1005)
pkg/kvstore/etcd.go:488:21: error strings should not be capitalized (ST1005)
pkg/kvstore/etcd.go:716:36: error strings should not be capitalized (ST1005)
pkg/kvstore/etcd.go:881:5: should omit comparison to bool constant, can be simplified to !txnresp.Succeeded (S1002)
pkg/kvstore/etcd_test.go:106:2: should merge variable declaration with assignment on next line (S1021)
pkg/kvstore/etcd_test.go:123:2: should use a simple channel send/receive instead of select with a single case (S1000)

Signed-off-by: Thomas Graf <thomas@cilium.io>