test/nat46x64: Fix out-of-bounds index error
In the NAT46x64 workflow, on several occasions, we delete the Cilium
pods and wait for them to be ready again. We do this by first retrieving
the Cilium pod name then waiting for it with "kubectl wait".

However, if we attempt to retrieve the pod name just between the
deletion of the previous pod and the scheduling of the new one, it fails
with the following error because no Cilium pod is present:

    ++ kubectl -n kube-system get pod -l k8s-app=cilium '-o=jsonpath={.items[0].metadata.name}'
    error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
    	    {.items[0].metadata.name}
        object given to jsonpath engine was:
    	    map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

We can avoid this by waiting for the daemonset rollout to be finished
instead.

Fixes: d959a955 ("cilium, tests: Add NAT46x64 standalone LB runtime test suite")
Signed-off-by: Paul Chaignon <paul@cilium.io>