helm: Fix Helm template for externalWorkloads
This fixes an error where instantiating the Helm chart with
`externalWorkloads.enabled=true` would fail due an invalid prefix
command in our Helm template:

```
Error: template: cilium/templates/clustermesh-apiserver/tls-helm/server-secret.yaml:4:11:
 executing "cilium/templates/clustermesh-apiserver/tls-helm/server-secret.yaml" at
  <prepend>: wrong number of args for prepend: want 2 got 3
```

Fixes: c24667b0ee07 ("refactor cert-gen logic")
Reported by: Slack user `night` on cilium.slack.com

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>