cmd/loadbalancer: Add API to update service backend states
The API will allow users to update backend states. The primary
motivation is to quarantine unreachable backends so that such
backends won't be selected for load-balancing service traffic.
Internally, the agent iterate over the services map, and update all
the services that select the updated backends. States transitions
are internally validated before updating the states.

See dump below to how to set "quarantine" state for backends.
Quarantined backends when become reachable can be set back to
the active state.

```

$ cilium service list
ID   Frontend          Service Type   Backend
4    10.96.95.246:80   ClusterIP      1 => 10.244.0.58:80 (active)
                                      2 => 10.244.1.59:80 (active)
                                      3 => 10.244.1.8:80 (active)

$ cilium service update --backends 10.244.0.58:80 --states quarantined
Updating backend states
Updated service with 1 backends

$ cilium service list
ID   Frontend          Service Type   Backend
4    10.96.95.246:80   ClusterIP      1 => 10.244.0.58:80 (quarantined)
                                      2 => 10.244.1.59:80 (active)
                                      3 => 10.244.1.8:80 (active)

$ cilium service update --backends 10.244.0.58:80 --states active
Updating backend states
Updated service with 1 backends

$ cilium service list
ID   Frontend          Service Type   Backend
4    10.96.95.246:80   ClusterIP      1 => 10.244.0.58:80 (active)
                                      2 => 10.244.1.59:80 (active)
                                      3 => 10.244.1.8:80 (active)

$ cilium service update --backends 10.244.0.58:80 --states terminating
Updating backend states
Updated service with 1 backends

e$ cilium service list
ID   Frontend          Service Type   Backend
4    10.96.95.246:80   ClusterIP      1 => 10.244.0.58:80 (terminating)
                                      2 => 10.244.1.59:80 (active)
                                      3 => 10.244.1.8:80 (active)

$ cilium service update --backends 10.244.0.58:80 --states active
Updating backend states
Error: Cannot add/update service: [PUT /service/{id}][501] putServiceIdUpdateBackendFailure  invalid state transition for backend[10.244.0.58:80] (terminating) -> (active) &{BackendAddresses:[0xc0000f8990] Flags:0xc0001004b0 FrontendAddress:0xc00012f9c0 ID:0}

```

Signed-off-by: Aditi Ghag <aditi@cilium.io>