workflows: Fix owner tag for stable branch workflows
GKE-based workflows on stable branches are currently failing with:

    ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Invalid field 'resource_labels.value': "v1.11". It must only contain lowercase letters ([a-z]), numeric characters ([0-9]), underscores (_) and dashes (-). International characters are allowed.

This commit therefore changes the owner tag for all workflows, to remove
the dot character.

Fixes: ad69e81d0b ("workflows: Fix SHA for scheduled runs on stable branches")
Signed-off-by: Paul Chaignon <paul@cilium.io>