github/workflows: Disable BIGTCP test
It looks like the test has never passed. Previously, on the Fedora VM we
were running on 5.11 kernel, while the BIGTCP feat requires 5.19.

Running the test fails either due to the missing log msg "Setting up
IPv6 BIG TCP" (due to the kernel requirement) or with the following:

    helm install <...>
    Error: INSTALLATION FAILED: Get
    "https://127.0.0.1:41711/apis/apps/v1/namespaces/kube-system/daemonsets/cilium":
    context deadline exceeded
    Error: Process completed with exit code 1.

Signed-off-by: Martynas Pumputis <m@lambda.lt>