datapath/loader: fix privileged test build
These got broken by commit fca06ad5ee80 ("datapath: always generate BTF
debug information") in PR #14166:

 	 # github.com/cilium/cilium/pkg/datapath/loader [github.com/cilium/cilium/pkg/datapath/loader.test]
	 pkg/datapath/loader/loader_test.go:198:24: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 pkg/datapath/loader/loader_test.go:255:28: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 pkg/datapath/loader/loader_test.go:283:27: too many arguments in call to compileDatapath
	 	have (context.Context, *directoryInfo, bool, bool, *logrus.Entry)
	 	want (context.Context, *directoryInfo, bool, *logrus.Entry)
	 make: *** [tests-privileged] Error 1

Fixes: fca06ad5ee80 ("datapath: always generate BTF
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>